### use balance
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId" : 1,
  "accountNumber" : "1000000001",
  "amount" : 20000
}


### cancel balance
POST http://localhost:8080/transaction/cancel
Content-Type: application/json

{
  "transactionId" : "2e9d31d08cc54e57969381e90d69ac9c",
  "accountNumber" : "1000000001",
  "amount" : 20000
}

